export enum Role {
  DOCTOR = 'DOCTOR',
  PATIENT = 'PATIENT',
  ADMIN = 'ADMIN',
}

export enum AppointmentStatus {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
  ATTENDED = 'ATTENDED',
}

export enum NotificationType {
  APPT_CREATED = 'APPT_CREATED',
  APPT_ACCEPTED = 'APPT_ACCEPTED',
  APPT_REJECTED = 'APPT_REJECTED',
  APPT_CANCELLED = 'APPT_CANCELLED',
  APPT_REMINDER = 'APPT_REMINDER',
  APPT_ATTENDED = 'APPT_ATTENDED',
  CHAT_MESSAGE = 'CHAT_MESSAGE',
}

export enum EventKind {
  APPOINTMENT_CREATED = 'APPOINTMENT_CREATED',
  APPOINTMENT_STATUS_CHANGED = 'APPOINTMENT_STATUS_CHANGED',
  APPOINTMENT_NOTE_ADDED = 'APPOINTMENT_NOTE_ADDED',
  CHAT_MESSAGE_SENT = 'CHAT_MESSAGE_SENT',
}
